function(si_add_device_access_driver name)
    add_library(${name} MODULE ${ARGN})
    target_link_libraries(${name} Qt5::Core SIDeviceAccess)
    set_target_properties(${name} PROPERTIES PREFIX "" SUFFIX ".sdd")
    install(TARGETS ${name} LIBRARY DESTINATION "${CMAKE_INSTALL_PREFIX}/${CMAKE_INSTALL_LIBEXECDIR}/openstuder/drivers")
endfunction()
