name: Packages
on:
  push:
    tags:
      - '*'
jobs:
  package-raspberry:
    name: Package for Raspberry Pi OS (32-bit) 2022-04-04
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build package for Raspberry Pi (ARM 32-bit)
        uses: pguyot/arm-runner-action@v2
        with:
          base_image: https://downloads.raspberrypi.org/raspios_lite_armhf/images/raspios_lite_armhf-2022-04-07/2022-04-04-raspios-bullseye-armhf-lite.img.xz
          cpu: cortex-a8
          image_additional_mb: 2048
          copy_artifact_path: build
          commands: |
            sudo apt-get update
            sudo apt-get install -yq g++ git cmake cmake-data ninja-build qtbase5-dev qtchooser qt5-qmake qtbase5-dev-tools libqt5serialport5-dev libqt5serialbus5-dev libqt5serialbus5-plugins libqt5websockets5-dev qtconnectivity5-dev
            cmake -G Ninja -B build -DCMAKE_BUILD_TYPE=Release
            cmake --build build --target package

      - name: Clone package repository
        uses: actions/checkout@v2
        with:
          repository: openstuder/ppa
          path: ppa
          ssh-key: '${{ secrets.PPA_GIT_PKEY }}'

      - name: Copy package into package repository
        run: cp ./build/*.deb ppa/

      - name: Update package index
        env:
          PPA_SIGN_EMAIL: '${{ secrets.PPA_SIGN_EMAIL }}'
          PPA_SIGN_KEY: '${{ secrets.PPA_SIGN_KEY }}'
        run: |
          cd ppa
          echo -e "$PPA_SIGN_KEY" | gpg --import
          dpkg-scanpackages --multiversion . > Packages
          gzip -k -f Packages
          apt-ftparchive release . > Release
          gpg --default-key "${PPA_SIGN_EMAIL}" -abs -o - Release > Release.gpg
          gpg --default-key "${PPA_SIGN_EMAIL}" --clearsign -o - Release > InRelease

      - name: Update PPA
        run: |
          cd ppa
          git config user.name ppa
          git config user.email ppa@www.openstuder.io
          git add -A
          git commit -m "Updated package index"
          git push origin
